server:
  port: 10014


#spring:
#  redis:
#    sentinel:
#      master: monitor-man   # master书写是使用哨兵监听的那个名称
#      nodes: 192.168.2.102:26379   # 连接的不再是一个具体redis主机,书写的是多个哨兵节点

#sentinelServersConfig:
#  idleConnectionTimeout: 10000
#  connectTimeout: 10000
#  timeout: 3000
#  retryAttempts: 3
#  retryInterval: 1500
#  password: null
#  subscriptionsPerConnection: 5
#  clientName: null
#  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
#  slaveSubscriptionConnectionMinimumIdleSize: 1
#  slaveSubscriptionConnectionPoolSize: 50
#  slaveConnectionMinimumIdleSize: 32
#  slaveConnectionPoolSize: 64
#  masterConnectionMinimumIdleSize: 32
#  masterConnectionPoolSize: 64
#  readMode: "SLAVE"
#  sentinelAddresses:
#    - "redis://192.168.2.102:26379"
##    - "redis://127.0.0.1:26389"
#  masterName: "monitor-man"
#  database: 0
#threads: 0
#nettyThreads: 0
#codec: !<org.redisson.codec.JsonJacksonCodec> {}
#"transportMode":"NIO"